#!/bin/zsh

if [ -f ~/.zshrc ]; 
then
	echo ".zshrc already exists in your home folder. Remove it first." 
	return 1
else 
	ln -s $(readlink -en $(dirname $0)/zshrc) ~/.zshrc 
fi
if [ -f ~/.vimrc ]; 
then
	echo ".vimrc already exists in your home folder. Remove it first." 
	return 1
else 
	ln -s $(readlink -en $(dirname $0)/vimrc) ~/.vimrc 
fi
