#!/bin/zsh

# Link to the zsh config
ln -s -f $(readlink -en $(dirname $0)/zshrc) ~/.zshrc

# Link to the vim config
ln -s -f $(readlink -en $(dirname $0)/vimrc) ~/.vimrc

# Install Vundle and all plugins
[ -d ~/.vim/bundle/Vundle.vim ] && rm -rf ~/.vim/bundle/Vundle.vim
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
vim +PluginInstall +qall

# Download a font needed for airline.
mkdir -p ~/.fonts
wget 'https://github.com/Lokaltog/powerline-fonts/raw/master/DejaVuSansMono/DejaVu Sans Mono for Powerline.ttf' \
    -O ~/.fonts/DejaVu\ Sans\ Mono\ for\ Powerline.ttf
fc-cache -f ~/.fonts

# Configure terminator with the font and set it as default
ln -s -f $(readlink -en $(dirname $0)/terminator_config) ~/.config/terminator/config
gsettings set org.gnome.desktop.default-applications.terminal exec 'terminator'

# Setup some git defaults
ln -s -f $(readlink -en $(dirname $0)/gitignore_global) ~/.gitignore_global
git config --global core.excludesfile ~/.gitignore_global
git config --global user.name "Alexander Hermans"
git config --global user.email "Alexander.Hermans0@gmail.com"
git config --global push.default "matching"
